### ISSUE TITLE
command line  --n_tiles 

### ISSUE THREAD

**Issue by romainGuiet** [stardist/stardist#191]
Hi @maweigert , Hi @uschmidt83 ,

**Describe the bug**
I try to make use of the command line  :
`stardist-predict3d -i _pathToImage_ -m _pathToModel_ -o _pathToOutputfolder_ `
which fails if I add the `--n_tiles ` as `--n_tiles 2 2 2` or `--n_tiles 2 2`
but works without it (on small image)

**To reproduce**
With :  `stardist-predict3d -i _pathToImage_ -m _pathToModel_ -o _pathToOutputfolder_ --n_tiles 2 2 2` 
I get 
```
usage: stardist-predict3d [-h] -i INPUT [INPUT ...] [-o OUTDIR]
                          [--outname OUTNAME [OUTNAME ...]] -m MODEL
                          [--axes AXES] [--n_tiles N_TILES N_TILES]
                          [--pnorm PNORM PNORM] [--prob_thresh PROB_THRESH]
                          [--nms_thresh NMS_THRESH] [-v]
stardist-predict3d: error: unrecognized arguments: 2
````

With :  `stardist-predict3d -i _pathToImage_ -m _pathToModel_ -o _pathToOutputfolder_ --n_tiles 2 2` 
I get 
```
2022-04-26 16:35:54.364571: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Using TensorFlow backend.
There is 1 registered model for 'StarDist3D':

Name        Alias(es)
────        ─────────
'3D_demo'   None
WARNING:tensorflow:From D:\conda_envs\stardistTF115\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Loading network weights from 'weights_best.h5'.
2022-04-26 16:35:57.772778: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2022-04-26 16:35:57.809744: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: NVIDIA GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:65:00.0
2022-04-26 16:35:57.810756: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2022-04-26 16:35:57.818601: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2022-04-26 16:35:57.825213: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2022-04-26 16:35:57.826615: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2022-04-26 16:35:57.833949: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2022-04-26 16:35:57.837974: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2022-04-26 16:35:57.855211: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2022-04-26 16:35:57.855740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2022-04-26 16:35:57.857508: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2022-04-26 16:35:57.867733: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: NVIDIA GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:65:00.0
2022-04-26 16:35:57.868545: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2022-04-26 16:35:57.869707: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2022-04-26 16:35:57.870808: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2022-04-26 16:35:57.872446: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2022-04-26 16:35:57.873565: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2022-04-26 16:35:57.874655: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2022-04-26 16:35:57.875731: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2022-04-26 16:35:57.876991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2022-04-26 16:35:58.325911: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-04-26 16:35:58.326367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2022-04-26 16:35:58.328631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2022-04-26 16:35:58.330088: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9531 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.482392, nms_thresh=0.4.
Traceback (most recent call last):
  File "D:\conda_envs\stardistTF115\lib\site-packages\stardist\models\base.py", line 363, in _predict_setup
    img.ndim == len(n_tiles) or _raise(TypeError())
  File "D:\conda_envs\stardistTF115\lib\site-packages\csbdeep\utils\utils.py", line 91, in _raise
    raise e
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\conda_envs\stardistTF115\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\conda_envs\stardistTF115\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\conda_envs\stardistTF115\Scripts\stardist-predict3d.exe\__main__.py", line 7, in <module>
  File "D:\conda_envs\stardistTF115\lib\site-packages\stardist\scripts\predict3d.py", line 85, in main
    nms_thresh=args.nms_thresh)
  File "D:\conda_envs\stardistTF115\lib\site-packages\stardist\models\base.py", line 677, in predict_instances
    prob_thresh=prob_thresh, show_tile_progress=show_tile_progress, **predict_kwargs)
  File "D:\conda_envs\stardistTF115\lib\site-packages\stardist\models\base.py", line 524, in predict_sparse
    self._predict_setup(img, axes, normalizer, n_tiles, show_tile_progress, predict_kwargs)
  File "D:\conda_envs\stardistTF115\lib\site-packages\stardist\models\base.py", line 365, in _predict_setup
    raise ValueError("n_tiles must be an iterable of length %d" % img.ndim)
ValueError: n_tiles must be an iterable of length 3
```

**Expected behavior**
StarDist runs normally 😅 

**Environment (please complete the following information):**
 - StarDist version [0.8.2]
 - CSBDeep version [0.6.3]
 - TensorFlow version [1.15]
 - OS: [Windows]
 - GPU memory (if applicable): [11 GB]

conda env made with yml 
```
name: stardist082_tf115
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - tensorflow-gpu=1.15.0
  - cudnn==7.6.5
  - cudatoolkit=10.0
  - nodejs>=6.11.5
  - ipywidgets
  - qtpy
  - qtconsole
  - scipy
  - scikit-image
  - vispy
  - ipython
  - pyopengl
  - pyside2
  - matplotlib
  - h5py==2.10.0
  - notebook
  - pip
  - pip:
    - jupyter-tensorboard
    - stardist==0.8.2
    - gputools
    - tabulate
    - albumentations
    - stardist-napari
    - pandas 
    - scikit-learn
    - keras

```

You may run this code and paste the output:
```python
import importlib, platform

print(f'os: {platform.platform()}')
for m in ('stardist','csbdeep','tensorflow'):
    try:
        print(f'{m}: {importlib.import_module(m).__version__}')
    except ModuleNotFoundError:
        print(f'{m}: not installed')

import tensorflow as tf
try:
    print(f'tensorflow GPU: {tf.test.is_gpu_available()}')
except:
    print(f'tensorflow GPU: {tf.config.list_physical_devices("GPU")}')
```
output :  

```
stardist: 0.8.2
csbdeep: 0.6.3
2022-04-26 17:09:29.604880: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
tensorflow: 1.15.0
>>> import tensorflow as tf
>>> try:
...     print(f'tensorflow GPU: {tf.test.is_gpu_available()}')
... except:
...     print(f'tensorflow GPU: {tf.config.list_physical_devices("GPU")}')
...
2022-04-26 17:10:02.762196: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2022-04-26 17:10:02.771352: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2022-04-26 17:10:02.817466: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: NVIDIA GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:65:00.0
2022-04-26 17:10:02.818832: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2022-04-26 17:10:02.832643: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2022-04-26 17:10:02.841572: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2022-04-26 17:10:02.844638: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2022-04-26 17:10:02.853304: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2022-04-26 17:10:02.858010: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2022-04-26 17:10:02.876670: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2022-04-26 17:10:02.877242: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2022-04-26 17:10:03.537027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-04-26 17:10:03.537499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2022-04-26 17:10:03.539815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2022-04-26 17:10:03.541601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:0 with 9531 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
tensorflow GPU: True
```

I think it’s the same issue as in the previous PR, only 2 arguments instead of 3 and was that it was solved with https://github.com/stardist/stardist/pull/177

**Comment by maweigert** [comment]
Sorry for the late reply.

You are using the `scripts` branch?

**Comment by romainGuiet** [comment]
Hi ,

>Sorry for the late reply.

no worries 😊

>You are using the scripts branch?

Actually, I'm not... I simply created a conda env with a yml file (see above) , specifying version  `stardist==0.8.2` (not specifying a the script branch)

I tried the `stardist-predict3d -h` and I saw it was there :
```
usage: stardist-predict3d [-h] -i INPUT [INPUT ...] [-o OUTDIR]
                          [--outname OUTNAME [OUTNAME ...]] -m MODEL
                          [--axes AXES] [--n_tiles N_TILES N_TILES]
                          [--pnorm PNORM PNORM] [--prob_thresh PROB_THRESH]
                          [--nms_thresh NMS_THRESH] [-v]

Prediction script for a 3D stardist model, usage: stardist-predict -i
input.tif -m model_folder_or_pretrained_name -o output_folder

optional arguments:
  -h, --help            show this help message and exit
  -i INPUT [INPUT ...], --input INPUT [INPUT ...]
                        input file (tiff) (default: None)
  -o OUTDIR, --outdir OUTDIR
                        output directory (default: .)
  --outname OUTNAME [OUTNAME ...]
                        output file name (tiff) (default: {img}.stardist.tif)
  -m MODEL, --model MODEL
                        model folder / pretrained model to use (default: None)
  --axes AXES           axes to use for the input, e.g. 'XYC' (default: None)
  --n_tiles N_TILES N_TILES
                        number of tiles to use for prediction (default: None)
  --pnorm PNORM PNORM   pmin/pmax to use for normalization (default: [3,
                        99.8])
  --prob_thresh PROB_THRESH
                        prob_thresh for model (if not given use model default)
                        (default: None)
  --nms_thresh NMS_THRESH
                        nms_thresh for model (if not given use model default)
                        (default: None)
  -v, --verbose
```
but I can't make it work 😑

**Comment by maweigert** [comment]
Yes, its currently only the `scripts` branch. You could list in in the yaml like so 

```
- pip: 
    - git+https://github.com/stardist/stardist.git@scripts
```

But then you do have to compile. We should merge into main and release it new.

**Comment by romainGuiet** [comment]
🤨 so it's there but it's not 😅 !

Thanks for your reply 😁

BTW the script branch is under 0.7.3 version so far 

Cheers,

R

**Comment by romainGuiet** [comment]
>The scripts branch was merged (https://github.com/stardist/stardist/pull/201) and the scripts are now part of [release 0.8.3](https://github.com/stardist/stardist/releases/tag/0.8.3). Does this solve your issues? 

Yeah 🎉 ! 

Thanks a lot
