### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by WXY-Belief** [stardist/stardist#207]
Hello, there exist the following error when  I running starlist.

"C:\Program Files\Anaconda\python.exe" D:/PycharmProjects/H&E/segmentation.py
2022-08-30 09:21:03.869117: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-08-30 09:21:03.869250: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(673, 1262)
Found model '2D_demo' for 'StarDist2D'.
2022-08-30 09:21:06.649692: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-08-30 09:21:06.649828: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-08-30 09:21:06.652341: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-LT7DTDJ
2022-08-30 09:21:06.652557: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-LT7DTDJ
2022-08-30 09:21:06.652966: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Loading network weights from 'weights_best.h5'.
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.486166, nms_thresh=0.5.
Traceback (most recent call last):
  File "D:/PycharmProjects/H&E/segmentation.py", line 123, in <module>
    segmentation(X)
  File "D:/PycharmProjects/H&E/segmentation.py", line 75, in segmentation
    pred, _ = model.predict_instances(normalize(img), **kwargs)
  File "C:\Users\24667\AppData\Roaming\Python\Python38\site-packages\stardist\models\base.py", line 775, in predict_instances
    for r in self._predict_instances_generator(*args, **kwargs):
  File "C:\Users\24667\AppData\Roaming\Python\Python38\site-packages\stardist\models\base.py", line 727, in _predict_instances_generator
    for res in self._predict_sparse_generator(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles,
  File "C:\Users\24667\AppData\Roaming\Python\Python38\site-packages\stardist\models\base.py", line 538, in _predict_sparse_generator
    self._predict_setup(img, axes, normalizer, n_tiles, show_tile_progress, predict_kwargs)
  File "C:\Users\24667\AppData\Roaming\Python\Python38\site-packages\stardist\models\base.py", line 381, in _predict_setup
    self.config.n_channel_in == x.shape[channel] or _raise(ValueError())
  File "C:\Users\24667\AppData\Roaming\Python\Python38\site-packages\csbdeep\utils\utils.py", line 91, in _raise
    raise e
ValueError

Process finished with exit code 1

**Comment by uschmidt83** [comment]
Dear @WXY-Belief, I'm sorry but this is a likely a usage error (`self.config.n_channel_in == x.shape[channel]` violated) and not a bug report. Please ask this question [at the forum](https://forum.image.sc/tag/stardist), as [instructed](https://github.com/stardist/stardist/issues/new/choose).
