### ISSUE TITLE
Stardist import fails in fresh installation (tensorflow.keras has no attribute __version__)

### ISSUE THREAD

**Issue by constantinpape** [stardist/stardist#241]
**Describe the bug**
I have a freshly installed stardist environment. `from stardist.models import StarDist2D` fails with `AttributeError: module 'tensorflow.keras' has no attribute '__version__'`. See full stacktrace below.

**To reproduce**
```python
from stardist.models import StarDist2D
```
fails with
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nimcpape/Work/software/conda/mambaforge/envs/stardist/lib/python3.10/site-packages/stardist/models/__init__.py", line 3, in <module>
    from .model2d import Config2D, StarDist2D, StarDistData2D
  File "/home/nimcpape/Work/software/conda/mambaforge/envs/stardist/lib/python3.10/site-packages/stardist/models/model2d.py", line 258, in <module>
    class StarDist2D(StarDistBase):
  File "/home/nimcpape/Work/software/conda/mambaforge/envs/stardist/lib/python3.10/site-packages/stardist/models/model2d.py", line 290, in StarDist2D
    def __init__(self, config=Config2D(), name=None, basedir='.'):
  File "/home/nimcpape/Work/software/conda/mambaforge/envs/stardist/lib/python3.10/site-packages/stardist/models/model2d.py", line 237, in __init__
    min_delta_key = 'epsilon' if LooseVersion(keras.__version__)<=LooseVersion('2.1.5') else 'min_delta'
AttributeError: module 'tensorflow.keras' has no attribute '__version__'
```

**Expected behavior**
It should work.

**Environment (please complete the following information):**
Here's the output from the code snippet you provide  in the Issue template:
```
os: Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28
stardist: 0.8.3
csbdeep: 0.7.3
tensorflow: 2.13.0
2023-07-18 14:54:48.813902: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /device:GPU:0 with 18025 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB MIG 3g.20gb, pci bus id: 0000:2f:00.0, compute capability: 8.0
tensorflow GPU: True
```
I have removed a couple of unrelated warnings for readability.

**Comment by uschmidt83** [comment]
Thanks for the bug report, this is going to be fixed soon.

(I just [updated `csbdeep`](https://github.com/CSBDeep/CSBDeep/releases/tag/0.7.4), `stardist` will follow later today.)

**Comment by constantinpape** [comment]
Thanks @uschmidt83 ! Happy to test it as soon as the releases are there :).

**Comment by hanslovsky** [comment]
Thank you @uschmidt83. I just ran into this and am glad that I am 6 hours behind

FYI, downgrading to tensorflow `2.12` fixes this as a temporary workaround for me.

**Comment by uschmidt83** [comment]
FYI, the [new release](https://github.com/stardist/stardist/releases/tag/0.8.4) is done.
It should fix the issue mentioned by @constantinpape.

**Comment by constantinpape** [comment]
I can confirm that it works now. Thanks @uschmidt83 !

**Comment by cosecdelta** [comment]
I ran into this issue. 
Tensorflow version: 2.15.0
Stardist: 0.8.3

I tried downgrading tensorflow to 2.12.0 but it did not work

![image](https://github.com/stardist/stardist/assets/63477668/b42ed1c0-3dbc-4e19-af88-be567b7d3fdb)

**Comment by uschmidt83** [comment]
Hi @cosecdelta, please upgrade StarDist to [version 0.8.5](https://github.com/stardist/stardist/releases/tag/0.8.5).
