### ISSUE TITLE
ValueError: axes (YXC) must be of length 2

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [stardist/stardist#280]
**Describe the bug**
I'm trying to do cell segmentation on a .tif image (HE) which I'm cropping to have shape (5012, 5012), but I keep getting an error that `ValueError: axes (YXC) must be of length 2.`. If I put axes="YX", it simply shows this:

```


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/work/RO_src/venv/stardist_venv/lib/python3.10/site-packages/stardist/models/base.py", line 788, in predict_instances
    for r in self._predict_instances_generator(*args, **kwargs):
  File "/mnt/work/RO_src/venv/stardist_venv/lib/python3.10/site-packages/stardist/models/base.py", line 740, in _predict_instances_generator
    for res in self._predict_sparse_generator(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles,
  File "/mnt/work/RO_src/venv/stardist_venv/lib/python3.10/site-packages/stardist/models/base.py", line 551, in _predict_sparse_generator
    self._predict_setup(img, axes, normalizer, n_tiles, show_tile_progress, predict_kwargs)
  File "/mnt/work/RO_src/venv/stardist_venv/lib/python3.10/site-packages/stardist/models/base.py", line 392, in _predict_setup
    self.config.n_channel_in == x.shape[channel] or _raise(ValueError())
  File "/mnt/work/RO_src/venv/stardist_venv/lib/python3.10/site-packages/csbdeep/utils/utils.py", line 89, in _raise
    raise e
ValueError


```
**To reproduce**
```
# %%
import numpy as np
from stardist.models import StarDist2D
from stardist.plot import render_label
from csbdeep.utils import normalize
import matplotlib.pyplot as plt
from PIL import Image

# Load the image
img = Image.open("/40x_BF_01.tif")

# Define the crop size
crop_size = (5012, 5012)

# Define the top-left corner of the cropping box
top_left_x = 300  # Example x coordinate
top_left_y = 300  # Example y coordinate

# Calculate the bottom-right corner based on the crop size
bottom_right_x = top_left_x + crop_size[0]
bottom_right_y = top_left_y + crop_size[1]

# Crop the image using the defined box
crop_box = (top_left_x, top_left_y, bottom_right_x, bottom_right_y)
cropped_img = img.crop(crop_box)

# Convert to grayscale and numpy array if needed
cropped_img = cropped_img.convert("L")  # Convert to grayscale (2D image)
cropped_img = np.array(cropped_img)  # Convert to numpy array

# Normalize the image
cropped_img = normalize(cropped_img)
# Load the pretrained StarDist model for H&E
model = StarDist2D.from_pretrained("2D_versatile_he")
# %%
# Predict instances with the correct axes specified
labels, _ = model.predict_instances(cropped_img, axes="YX")

# %%
# Plot the results
plt.subplot(1, 2, 1)
plt.imshow(cropped_img, cmap="gray")
plt.axis("off")
plt.title("Cropped Input Image")
# %%
plt.subplot(1, 2, 2)
plt.imshow(render_label(labels, img=cropped_img))
plt.axis("off")
plt.title("Prediction + Input Overlay")
plt.show()



```

**Data and screenshots**
If applicable, add data (e.g. images) or screenshots to help explain your problem.
I'm able to see the greyed out image using the L formatting, so the image is being loaded:

![image](https://github.com/user-attachments/assets/9c1d2447-3c30-442f-8a10-77fd66f06afc)

**Environment (please complete the following information):**
Latest packages for stardist and tensorflow
```

**Comment by maweigert** [comment]
The `2D_versatile_he` model expects the input to be a (normalized) RGB array, i.e. `img.shape=(N,M,3)`
