### ISSUE TITLE
Error while trying to load model

### ISSUE THREAD

**Issue by Teranis** [stardist/stardist#287]
**Describe the bug**
Error while trying to load model.

**To reproduce**
```python

from stardist.models import StarDist2D

model_name = '2D_versatile_fluo'
model = StarDist2D.from_pretrained(model_name)

```

**Expected behavior**
Get model for later segmentation

**Data and screenshots**
If applicable, add data (e.g. images) or screenshots to help explain your problem.

**Error Msg:**
Found model '2D_versatile_fluo' for 'StarDist2D'.
Traceback (most recent call last):
  File "c:\Users\timon\Cell_ACDC\cellacdc\test.py", line 4, in <module>
    model = StarDist2D.from_pretrained(model_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\timon\venvs\acdc_dev\Lib\site-packages\csbdeep\models\base_model.py", line 130, in from_pretrained
    return get_model_instance(cls, name_or_alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\timon\venvs\acdc_dev\Lib\site-packages\csbdeep\models\pretrained.py", line 116, in get_model_instance
    path = get_model_folder(cls, key_or_alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\timon\venvs\acdc_dev\Lib\site-packages\csbdeep\models\pretrained.py", line 108, in get_model_folder
    path_folder.symlink_to(path.relative_to(path.parent))
  File "C:\Users\timon\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1386, in symlink_to
    os.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: '2D_versatile_fluo_extracted' -> 'C:\\Users\\timon\\.keras\\models\\StarDist2D\\2D_versatile_fluo\\2D_versatile_fluo'

**Environment (please complete the following information):**
os: Windows-11-10.0.22631-SP0
stardist: 0.9.1
csbdeep: 0.8.1
2024-11-22 16:31:38.032800: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-22 16:31:38.726467: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
tensorflow: 2.18.0
WARNING:tensorflow:From c:\Users\timon\Cell_ACDC\cellacdc\test.py:17: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2024-11-22 16:31:40.590529: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags. 
tensorflow GPU: False

**Comment by nicofunke** [comment]
Any updates?

**Comment by nicofunke** [comment]
It seems like the bug is due to windows not enabling symbolic links by default. After enabling symbolic links in windows the error was gone.

There are two ways to enable symbolic links in windows: 
1. Enable developer mode in windows settings
2. Modify user rights to allow creation of symbolic links

You can find instructions on how to enable symbolic links in windows here: https://neacsu.net/posts/win_symlinks/
